var textArray = [
  'Ad: <a href = "https://www.ohsu.edu">Oregon Health & Science University | Healing Begins With Discovery</a>',
  'Ad: <a href = "https://www.jhu.edu/">Johns Hopkins University | Research Saves Lives</a>',
  'Ad: <a href = "https://www.fredhutch.org/en.html?gad_source=1">Fred Hutch Cancer Center | Science Meets Care</a>',
  'Ad: <a href = "https://www.libd.org/">Lieber Institute for Brain Development | Unlocking Mysteries of the Brain</a>',
  'Ad: <a href = "https://www.washington.edu/">University of Washington | Be Boundless</a>',
  'Ad: <a href = "https://www.ohsu.edu/knight-cancer-institute">Knight Cancer Research Institute | Driven to cure cancer. Devoted to caring for you.</a>',
  'Ad: <a href = "https://xkcd.com/">XKCD | A Webcomic of romance, sarcasm, math, and language</a>',
  'Ad: <a href = "https://theoatmeal.com/">The Oatmeal | Comics by Matthew Inman</a>',
  'Ad: <a href = "https://www.bioconductor.org/">Bioconductor | Open source software for bioinformatics</a>',
  'Ad: <a href = "https://www.kexp.org/">KEXP | Where the Music Matters</a>',
  'Ad: <a href = "https://www.redbubble.com/people/rainbowrat23/shop">Shop designs by rainbowrat23 | Visit Redbubble</a>',
  'Ad: <a href = "https://planetquestionmark.bandcamp.com/album/cheesytruths-proper-mix">Rainbow Rat - Cheesy Truths (Digital album out now) | Visit Bandcamp</a>'
];
var randomNumber1 = Math.floor(Math.random() * textArray.length);
var randomNumber2 = Math.floor(Math.random() * textArray.length);
var randomNumber3 = Math.floor(Math.random() * textArray.length);
var randomNumber4 = Math.floor(Math.random() * textArray.length);
var randomNumber5 = Math.floor(Math.random() * textArray.length);
var randomNumber6 = Math.floor(Math.random() * textArray.length);
var randomNumber7 = Math.floor(Math.random() * textArray.length);
var randomNumber8 = Math.floor(Math.random() * textArray.length);
var randomNumber9 = Math.floor(Math.random() * textArray.length);
var randomNumber10 = Math.floor(Math.random() * textArray.length);
var randomNumber11 = Math.floor(Math.random() * textArray.length);
var randomNumber12 = Math.floor(Math.random() * textArray.length);
document.getElementById("randomAd1").innerHTML = textArray[randomNumber1];
document.getElementById("randomAd2").innerHTML = textArray[randomNumber2];
document.getElementById("randomAd3").innerHTML = textArray[randomNumber3];
document.getElementById("randomAd4").innerHTML = textArray[randomNumber4];
document.getElementById("randomAd5").innerHTML = textArray[randomNumber5];
document.getElementById("randomAd6").innerHTML = textArray[randomNumber6];
document.getElementById("randomAd7").innerHTML = textArray[randomNumber7];
document.getElementById("randomAd8").innerHTML = textArray[randomNumber8];
document.getElementById("randomAd9").innerHTML = textArray[randomNumber9];
document.getElementById("randomAd10").innerHTML = textArray[randomNumber10];
document.getElementById("randomAd11").innerHTML = textArray[randomNumber11];
document.getElementById("randomAd12").innerHTML = textArray[randomNumber12];

