var textArray = [
  "<h3 style='font-size: 20;color: white'><i>\"I have read heaps of agricultural \& horticultural books, \& have never ceased collecting facts— At last gleams of light have come, \& I am almost convinced (quite contrary to opinion I started with) that species are not (it is like confessing a murder) immutable.\"</i><br><br>--Charles Darwin, British naturalist & biologist who first proposed evolution by natural selection</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"All models are false, but some are useful.\"</i><br><br>--George Box, British statistician</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"There were no textbooks, so we had to write them.\"</i><br><br>--Katherine Johnson, American mathematician and famous NASA researcher</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"If you want to change the future, start living as if you\'re already there.\"</i><br><br>--Lynn Conway, American computer scientist and electrical engineer</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"The end of a melody is not its goal.\"</i><br><br>--Friedrich Nietzsche, German philosopher, from 'The Wanderer and His Shadow'</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"The source of health boundaries is self-love and self-respect. When you learn to love yourself, you are less likely to put up with people who don\'t love you back.\"</i><br><br>--James Clear, American writer and author of 'Atomic Habits'</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"If I were to give an award for the single best idea anyone has ever had, I\'d give it to Darwin, ahead of Newton \& Einstein and everyone else. In a single stroke, the idea of evolution by natural selection unifies the realm of life, meaning, and purpose, with the realm of physical law.\"</i><br><br>--Daniel Dennet, American philosopher and author of 'Darwin\'s Dangerous Idea'</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"Start by cutting off the valleys of unhappiness, the things that tend to make you actively unhappy. The best way to start being more happy is to stop being unhappy.\"</i><br><br>--Richard Koch, British writer, from 'The Eighty Twenty Principle'</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"There is something about growth of 40 to 2000 percent per annum that makes you feel on top of the world. These companies know something that other firms do not...It is a kind of drug, but with only pleasant side effects.\"</i><br><br>--Richard Koch, British writer, from 'The Eighty Twenty Principle'</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"Those who suffer for others do more damage to humanity than those who enjoy themselves.\"</i><br><br>--Michael Patrini, Italian author, activist, and founder of the Slow Food Movement</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"[The Matthew Effect] is those who are successful, in other words, who are most likely to be given the kinds of special opportunities that lead to further success.\"</i><br><br>--Malcom Gladwell, from 'Outliers'</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"The future is already here-it\'s just not equally distributed.\"</i><br><br>--William Gibson, American-Canadian writer and author of The Sprawl trilogy of sci-fi novels</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"Create more than you consume.\"</i><br><br>--Simon Alexander Ong, entrepreneur and career coach</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"Merely stating a truth isn\'t enough. The truth has to be made vivid, interesting, and dramatic. You have to use showmanship.\"</i><br><br>--Dale Carnegie, American writer and teacher</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"When it comes to creative work, limitations mean freedom.\"</i><br><br>--From 'Steal Like an Artist' by Austin Kleon, American writer</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"Complain about the way other people make software by making software.\"</i><br><br>--Andre Torrez, from 'Steal Like an Artist' by Austin Kleon</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"The work you do while you procrastinate is probably the work you should be doing for the rest of your life.\"</i><br><br>--Jessica Hirsche, American lettering artist and writer</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"[Parkinson\'s Law is that] work expands to fill the time allotted.\"</i><br><br>--Cyril Northcote Parkinson, British historian</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"She rescued me. I\'d be playing in a steakhouse right now if it wasn\'t for her. I wouldn\'t even be playing in a steakhouse, I\'d be cooking in a steakhouse.\"</i><br><br>--Tom Waits, American musician, on wife Kathleen Brennan</h3>",
  "<h3 style='font-size: 20;color: white';><i>\"Cyberspace. A consensual hallucination experienced daily by billions of legitimate operators, in every nation, by children being taught mathematical concepts... A graphic representation of data abstracted from banks of every computer in the human system. Unthinkable complexity. Lines of light ranged in the nonspace of the mind, clusters and constellations of data.\"</i><br><br>--William Gibson, American-Canadian writer, from 'Neuromancer'</h3>"
];
var randomNumber = Math.floor(Math.random() * textArray.length);
document.getElementById("randomQuote").innerHTML = textArray[randomNumber];

